### ISSUE TITLE
Option -g must write npge.conf to disk

### ISSUE THREAD

**Issue by MaximNikolaev** [npge/npge#11]
Option `-g` must write npge.conf to disk
Reasons:
1. No way in redirecting stdout to somewhere else in Windows cmd.
2. Do not expect a user to know how to use `>>` in Linux bash.

**Comment by starius** [comment]
Current help message is as follows:

```
...
   -g                   generate config ('-g npge.conf' writes npge.conf)
...
```

Run `npge -g npge.conf` to create `npge.conf`.
