### ISSUE TITLE
Minor fix for UPX in package.sh for Win-x64 build

### ISSUE THREAD

**Issue by MaximNikolaev** [npge/npge#7]
As stated here http://sourceforge.net/p/upx/bugs/184/, UPX-packer does not support compressing 64 bit windows executables.
So it seems line 62 in `windows/package.sh.in`

``` sh
upx -9 npge-${VERSION}/*.exe
```

throws error for X86_64 arch.

**Comment by starius** [comment]
Thank you, Maxim!
